from ibllib.pipes import base_tasks
from ibllib.oneibl.data_handlers import ExpectedDataset

class PMD(base_tasks.MesoscopeTask):

    @property
    def signature(self):
        # The number of in and outputs will be dependent on the number of input raw imaging folders and output FOVs
        I = ExpectedDataset.input  # noqa
        signature = {
            'input_files': [I('_suite2p_ROIData.raw.zip', 'alf/FOV*', True, unique=False),
                            I('imaging.frames_motionRegistered.bin', 'suite2p/plane*', True, unique=False)],
            # FIXME come up with dataset names for outputs
            'output_files': [('imaging.sparse1.sparse_npz', 'alf/FOV*', True),
                             ('imaging.sparse2.sparse_npz', 'alf/FOV*', True),
                             ('imaging.dense.npz', 'alf/FOV*', True),
                             ('model.weights.npy', 'alf/FOV*', False)]  # False = not required output
        }
        return signature

    def _run(self, **kwargs):
        """
        Run the PMD processing task.

        Parameters
        ----------
        kwargs
            Optional parameters that may be used in the future.
        
        Returns
        -------
        file_paths : list of pathlib.Path
            List of file paths that were processed or generated by this task.
        """
        # This task is a stub for now, it will be implemented in the future
        raise NotImplementedError('PMD processing is not yet implemented.')
        self.train_model()
        self.compress_data()
        self.run_qc() # update dataset QC fields and upload visualizations as images/GIF notes
        return file_paths
    

import unittest

class TestPMD(unittest.TestCase):

    def setUp(self):
        self.session_path = '/path/to/subject/YYYY-MM-DD/XXX'
        self.pmd_task = PMD(self.session_path)

    def test_pmd_processing(self):
        # This is a placeholder for the actual test implementation
        # It should test the PMD processing pipeline
        with self.assertRaises(NotImplementedError):
            self.pmd_task._run()


if __name__ == '__main__':
    unittest.main()