name: CI

on:
  schedule:
    - cron:  '0 0 * * *'  # every day at midnight
  workflow_dispatch:  # For manual trigegring
  push:
    branches: [ master, develop, github-actions ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        os: ["ubuntu-latest", "windows-latest"]  #  , "macos-latest"
        python-version: ["3.7", "3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r requirements.txt
        pip install -e .
    - name: Configure ONE
      env:
        HTTP_DATA_SERVER_PWD: ${{ secrets.HTTP_DATA_SERVER_PWD }}
      run: |
        python -c "from oneibl.one import ONE; ONE(silent=True)"
        python ibllib/pipes/set_pass.py $HTTP_DATA_SERVER_PWD
    - name: Flake8
      run: |
        python -m flake8
    - name: ALF tests
      run: |
        cd alf
        python -m unittest discover --verbose
    - name: Brainbox tests
      run: |
        cd brainbox
        python -m unittest discover --verbose
    - name: oneibl tests
      run: |
        cd oneibl
        python -m unittest discover --verbose
    - name: ibllib tests
      run: |
        cd ibllib
        cd tests
        python -m unittest discover --verbose
