name: CI

on:
  schedule:
    - cron:  '0 0 * * *'  # every day at midnight
  workflow_dispatch:  # For manual triggering
  push:
    branches: [ master, develop, public ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Whether to stop execution of other instances
      max-parallel: 2
      matrix:
        os: ["windows-latest", "ubuntu-latest"]
        python-version: ["3.8", "3.11"]
        exclude:
          - os: windows-latest
            python-version: 3.8
          - os: ubuntu-latest
            python-version: 3.11
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest flake8-docstrings
        pip install -r requirements.txt
        pip install -e .
    - name: Flake8
      run: |
        python -m flake8
        python -m flake8 --select D --ignore E ibllib/qc/camera.py ibllib/qc/task_metrics.py
    - name: Brainbox tests
      run: |
        cd brainbox
        pytest
    - name: ibllib tests
      run: |
        cd ibllib
        cd tests
        python -m unittest discover
