# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the selected branches
on:
  schedule:
    - cron:  '0 0 * * *'  # every day at midnight
  workflow_dispatch:  # For manual trigegring
  push:
    branches: [ master, develop, github-actions ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#           conda install -y -c anaconda tk
#           pip install setuptools wheel packaging
jobs:
  incubator:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        os: ["ubuntu-latest"]  #  , "windows-latest", "macos-latest"
        python-version: ["3.7"]  # , "3.8"
    steps:
      - name: Install python3-tk tk-dev
        run: |
          sudo apt-get install tk-dev python3-tk
      - name: Clone ibllib repo
        uses: actions/checkout@v2
      - name: Install repo
        run: |
          pip install -r requirements.txt
          pip install -e .
      - name: Configure ONE
        env:
          HTTP_DATA_SERVER_PWD: ${{ secrets.HTTP_DATA_SERVER_PWD }}
        run: |
          python -c "from oneibl.one import ONE; ONE(silent=True)"
          python ibllib/pipes/set_pass.py "$HTTP_DATA_SERVER_PWD"
      - name: Flake8
        run: |
          python -m flake8
      - name: ALF tests
        run: |
          cd alf
          python -m unittest discover --verbose
      - name: Brainbox tests
        run: |
          cd brainbox
          python -m unittest discover --verbose
      - name: ibllib tests
        run: |
          cd ibllib
          python -m unittest discover --verbose
      - name: oneibl tests
        run: |
          cd oneibl
          python -m unittest discover --verbose
