name: Unit Tests (GitHub Actions)

on:
  workflow_dispatch:  # For manual triggering
  push:
    branches: [ master, develop, ci ]
  pull_request:
    branches: [ "*" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"
      - name: install ruff
        run: python -m pip install --upgrade pip ruff
      - name: ruff format
        run: python -m ruff format --check .
      - name: ruff check
        if: always()
        run: python -m ruff check .
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    needs: ruff
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Whether to stop execution of other instances
      max-parallel: 2
      matrix:
        os: ["windows-latest", "ubuntu-latest"]
        python-version: ["3.10", "3.13"]
        exclude:
          - os: windows-latest
            python-version: 3.10
          - os: ubuntu-latest
            python-version: 3.13
    env:
      ONE_SAVE_ON_DELETE: false
    steps:
    - uses: actions/checkout@v7
    - name: Install uv
      uses: astral-sh/setup-uv@v10.0.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install deps
      run: uv sync --locked --group dev
    - name: Flake8 & ruff
      run: |
        uv run ruff check .
        uv run flake8 --select D --ignore E ibllib/qc/camera.py ibllib/qc/task_metrics.py
    - name: Brainbox tests
      run: |
        cd brainbox
        uv run pytest
    - name: ibllib tests
      run: |
        cd ibllib/tests
        uv run python -m unittest discover
